<?php
/**
 * Opaque-session auth strategy (default).
 *
 * @package AestheticsLink\B2BAuth
 */

defined('ABSPATH') || exit;

/**
 * Server-issued opaque tokens, HMAC-hashed in a custom sessions table.
 *
 * - Token: 32 random bytes (64 hex chars) generated by random_bytes(),
 *   falling back to wp_generate_password() if the CSPRNG is unavailable.
 * - Storage: hash_hmac('sha256', $token, wp_salt('auth')) in the
 *   {prefix}al_b2b_sessions table along with user_id and expires_at.
 * - TTL: AL_B2B_SESSION_TTL (30 days by default).
 * - Revocation: per-token DELETE; password reset triggers
 *   revoke_all_sessions() to invalidate every other device.
 *
 * This is the security-preferred default: tokens never round-trip with
 * user data attached, the DB is the source of truth, and revocation is
 * O(1).
 */
class AL_B2B_Auth_Opaque_Session_Strategy implements AL_B2B_Auth_Strategy_Interface {

	public function resolve_user_id_from_token(string $token): int {
		global $wpdb;

		$token = trim($token);
		if ($token === '') {
			return 0;
		}

		$table = $this->table_name();
		$hash  = $this->hash_token($token);

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery
		$row = $wpdb->get_row(
			$wpdb->prepare(
				"SELECT user_id, expires_at FROM {$table} WHERE token_hash = %s LIMIT 1",
				$hash
			)
		);

		if (!$row || !isset($row->user_id, $row->expires_at)) {
			return 0;
		}

		$expires_ts = strtotime((string) $row->expires_at . ' UTC');
		if (!$expires_ts || $expires_ts < time()) {
			$this->revoke_session($token);
			return 0;
		}

		$user_id = (int) $row->user_id;
		if ($user_id <= 0) {
			return 0;
		}

		// Confirm the user still exists; clean up the session if not.
		if (!get_user_by('id', $user_id)) {
			$this->revoke_session($token);
			return 0;
		}

		return $user_id;
	}

	public function issue_session(int $user_id): ?string {
		global $wpdb;

		if ($user_id <= 0) {
			return null;
		}

		try {
			$token = bin2hex(random_bytes(32));
		} catch (Exception $exception) {
			$token = wp_generate_password(64, false, false);
		}

		$inserted = $wpdb->insert(
			$this->table_name(),
			array(
				'token_hash' => $this->hash_token($token),
				'user_id'    => $user_id,
				'expires_at' => gmdate('Y-m-d H:i:s', time() + AL_B2B_SESSION_TTL),
			),
			array('%s', '%d', '%s')
		);

		return $inserted ? $token : null;
	}

	public function revoke_session(string $raw_token): void {
		global $wpdb;

		if ($raw_token === '') {
			return;
		}

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery
		$wpdb->delete(
			$this->table_name(),
			array('token_hash' => $this->hash_token($raw_token)),
			array('%s')
		);
	}

	public function revoke_all_sessions(int $user_id): void {
		global $wpdb;

		if ($user_id <= 0) {
			return;
		}

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery
		$wpdb->delete(
			$this->table_name(),
			array('user_id' => $user_id),
			array('%d')
		);
	}

	public function cleanup_expired(): void {
		global $wpdb;

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.PreparedSQL.NotPrepared
		$wpdb->query(
			$wpdb->prepare(
				"DELETE FROM {$this->table_name()} WHERE expires_at <= %s",
				gmdate('Y-m-d H:i:s')
			)
		);
	}

	private function table_name(): string {
		global $wpdb;
		return $wpdb->prefix . AL_B2B_SESSION_TABLE;
	}

	private function hash_token(string $token): string {
		return hash_hmac('sha256', $token, wp_salt('auth'));
	}
}
